README.md
=> Update Nolan's Role

README.md
=> Updated emilie's github username

README.md
have a last review of the README file after updates before submission
=> Review the README file

src/App.js, src/Components/Layout/Navigation.js, src/Components/Pages/SignInPage.js
I added the sign in page. It was task 60 from Scrum Board. Please Review and let me know what you think. 
Thank you!
=> Add sign in

src/App.js, src/Components/Layout/Navigation.js, src/Components/Pages/HomePage.js, src/Components/Pages/SignUpPage.js
=> Fix: change "sign in" to "sign up"

src/App.js, src/Components/Layout/Navigation.js, src/Components/Pages/LoginPage.js
=> AddLoginPage

README.md
Modified README to reflect Project Description and Core Features.
=> Modified README to reflect Project Description and Core Features.

src/Components/Pages/SignUpPage.js
- Removed verify e-mail box & verify password box;
- Added the option to select the account type;
- Centered the create account button.
=> Sign Up Page Update - Pull Request

src/Components/Pages/LoginPage.js
Added password textbox.
Fixed page's texts and elements size scaling and alignment.
=> LoginPage Fixes

backend/server.js, frontend/src/App.js, frontend/src/Components/ItemCard.js, frontend/src/Components/Layout/Navigation.js, frontend/src/Components/Pages/ManageProfilePage.js
Add API end point to add order to database
=> Add API end point to add order to database

backend/server.js
Create API end-point that receives account name and password and returns the object of the account
=> API end-point login user (authentication)

frontend/src/Components/Cart.js, frontend/src/Components/ItemCard.js, frontend/src/Components/Pages/ItemDetailsPage.js, frontend/src/Components/Pages/ShoppingCartPage.js
- Added comments to functions and keywords for the Cart implementation.
=> Comments for Add To Cart | Pull Request

frontend/package-lock.json, frontend/package.json, frontend/src/App.test.js, package-lock.json
- Added testing .js files to test the three features developed for this sprint. Used reac testing library and jest.
=> Automated testing features

frontend/src/Components/Pages/ManageProfilePage.js
Manage Profile(frontend) Linked to updateUserAccountInfo (backend)
=> Manage Profile linked to updateUserAccountInfo

.vscode/launch.json, backend/package-lock.json, backend/package.json, backend/server.js, frontend/src/Components/Pages/SignUpPage.js
Link sign up page to a request that will write a new account in the database
=> Signup page linked to send request to backend

README.md
updating my role because Im working more on backend and linking frontend and backend in this project.
=> Updated READ ME to reflect Emilie's Role

frontend/src/Components/Pages/LoginPage.js
=> Fix: Now you cannot log in with empty fields

backend/server.js
https://we.tl/t-CLbUsbdQYk
Video of how this works
=> Create an API endpoint to add a product to the database

backend/server.js
API Seller can view all products they listed for sale
=> API see all items I have posted as a seller

backend/server.js
API endpoint for seller to modify product
=> modify a product to the database

backend/server.js
API to delete product listed by seller
=> delete seller product using _id (SKU) of product

frontend/src/Components/Pages/ShoppingCartPage.js
I added a Place order button. 
The button should only be seen when the user is logged in. 
The button then sends the order to the database as a list and includes each items description and id.
=> Added a Place Order button that sends to database.

backend/server.js
Added comments and organized within server. I would like to eventually separate these by features rather than having them all on server.js
=> Restructured Backend (Server)

backend/server.js, frontend/src/App.js, frontend/src/Components/Cart.js, frontend/src/Components/Pages/CustomerOrdersPage.js, frontend/src/Components/Pages/ShoppingCartPage.js, frontend/src/Components/Pages/SignUpPage.js
In this PR I also made sure that signing up and placing an order took the user back to the main page. I also improved some code on the ShoppingCartPage.
I also had to made sure the API endpoint to get Orders from database was a POST request and not a GET request.
I also fixed a bug where the browser would repeatedly send the HTTP request "get all products".
=> MyOrders now shows the orders of a user

backend/server.js
I used `seller_id := 1`.
Looking at the database there are 5 orders with at least one product with `seller_id := 1`
=> add api get endpoint orders by seller id

backend/server.js
This was tested with postman. It is able to delete an order in the database based on the order id.
=> API endpoint to delete an Order

frontend/src/Components/Pages/ShoppingCartPage.js
- Added the "Delete from Cart" button;
- Added the functionality to remove items from the cart.
Please write any suggestions you would like to make!
=> Remove Items from Cart | Pull Request

frontend/src/Components/Layout/Navigation.js
I changed the Navigation bar to make it look a little like amazon.
=> changed the navigation bar

frontend/src/Components/Pages/CustomerOrdersPage.js
I added a Cancel button in the MyOrders page. 
I also linked it to the backend. 
Deleting an order should work!
=> Add Cancel Button for Order + Linked to backend

backend/server.js, frontend/src/App.js, frontend/src/Components/Layout/Navigation.js, frontend/src/Components/Pages/AddItemForm.js, frontend/src/Components/Pages/CustomerOrdersPage.js
Created AddItemForm.js page.
Increased data limit of HTTP request to server backend.
Fixed bug "Unexpected use of confirm()" in CustomerOrderPage.js
Created navbar button to add item for sale for seller only.
=> Seller's add item form

backend/server.js, frontend/src/App.js, frontend/src/Components/Layout/Navigation.js, frontend/src/Components/Pages/MyProductsPage.js
- Seller can see "My Products" and it will redirect to the list of products that corresponds to the seller ID.
- Create the list of products AND the navbar button
- Link the list of products to the back end
- Now the user can delete an order from its "My products" and it is deleted in the database
=> My products page

backend/server.js, frontend/src/Components/Pages/MyProductsPage.js
- created an API endpoint to get all users from DataBase
- Changed the layout of the MyProducts
This is linked to the task #116
=> Get all users

backend/server.js
- now you can delete a user from the database based on the users ID
=> Delete user from Database

frontend/src/App.js, frontend/src/Components/Layout/Navigation.js, frontend/src/Components/Pages/UsersList.js
Created page for admins only that would display every users from the database showing their full name, email and account type.
Modified route path and navigation bar so that only admins can see and access it.
This is task #118.
=> Created users list page

backend/server.js
=> Undo Mistake

frontend/src/Components/Pages/AddItemForm.js, frontend/src/Components/Pages/ManageProfilePage.js, frontend/src/Components/Pages/UsersList.js
An admin can now edit all profiles
=> Admin can edit all profiles
